# Generated by Django 6.0.2 on 2026-02-13 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('sajeel', 'Sajeel'), ('mahrukh', 'Mahrukh')], max_length=50)),
                ('date', models.DateField()),
                ('fajr', models.BooleanField(default=False)),
                ('dhuhr', models.BooleanField(default=False)),
                ('asr', models.BooleanField(default=False)),
                ('maghrib', models.BooleanField(default=False)),
                ('isha', models.BooleanField(default=False)),
                ('tahajjud', models.BooleanField(default=False)),
                ('quran_read', models.BooleanField(default=False)),
                ('quran_pages', models.IntegerField(default=0)),
                ('quran_surah', models.CharField(blank=True, default='', max_length=200)),
                ('exercise', models.BooleanField(default=False)),
                ('no_junk_food', models.BooleanField(default=False)),
                ('wake_early', models.BooleanField(default=False)),
                ('dua_after_salah', models.BooleanField(default=False)),
                ('dhikr', models.BooleanField(default=False)),
                ('sadaqah', models.BooleanField(default=False)),
                ('water', models.IntegerField(default=0)),
                ('sleep_hours', models.FloatField(default=0)),
                ('mood', models.IntegerField(default=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('person', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('done', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.dailytracker')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
